
name: tams
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  convex_bottom_bar: ^3.0.0
  image_picker: ^1.0.0
  permission_handler: ^11.3.1
  table_calendar: ^3.0.0
  url_launcher: ^6.0.20
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.0
  awesome_dialog: ^3.1.1
  flutter_spinkit: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.1.0
  flutter_native_splash: ^2.0.4
  rive_common: ^0.4.10
  animate_do: ^3.3.4
  share_plus: ^10.0.0
  device_info_plus: ^10.1.1
  photo_view: ^0.15.0
  dio: ^5.1.1
  image_gallery_saver: ^2.0.3
  path_provider: ^2.0.11
  path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/Images/Python-Intrerview-Q&A-copy.webp
    - Assets/Images/logo-search-grid-2x.png
    - Assets/Images/ali-morshedlou-WMD64tMfc4k-unsplash.jpg
    - Assets/Images/noticeboard.png
    - Assets/Images/sih2024-problem-statement-live.png