
name: tams
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  convex_bottom_bar: ^3.0.0
  image_picker: ^1.0.0
  permission_handler: ^10.2.0
  table_calendar: ^3.0.0
  url_launcher: ^6.1.10  # Update to latest version
  android_intent_plus: ^4.0.0  # Update to latest version
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.0
  animate_do: ^2.1.0
  awesome_dialog: ^3.1.1
  flutter_spinkit: ^5.0.0
  image_cropper: ^1.4.1
  smooth_page_indicator: ^1.2.0+3 # Add the latest version


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/Images/Python-Intrerview-Q&A-copy.webp
    - Assets/Images/logo-search-grid-2x.png
    - Assets/Images/ali-morshedlou-WMD64tMfc4k-unsplash.jpg
    - Assets/Images/board.png
    - Assets/Documents/dummy-pdf_2.pdf